const actionTypes = {
  GET_HOME: "GET_HOME",
  GET_CURRENT_SONG_ID: "GET_CURRENT_SONG_ID",
  SET_CURRENT_SONG_DATA: "SET_CURRENT_SONG_DATA",
  SET_CURRENT_ALBUM_ID: "SET_CURRENT_ALBUM_ID",
  SET_RECENT: "SET_RECENT",

  // Music
  PLAY: "PLAY",
  ERROR: "ERROR",
  SET_ALBUM: "SET_ALBUM",
  PLAYLIST: "PLAYLIST",
  LOADING: "LOADING",
};

export default actionTypes;
